export const GET_PAGE_BY_NUMBER = 'GET_PAGE_BY_NUMBER';
export const GET_PAGE_SUCCESS = 'GET_PAGE_SUCCESS';
export const GET_PAGE_ERROR = 'GET_PAGE_ERROR';

export const POST_USERS = 'POST_USERS';
export const POST_USERS_SUCCESS = 'POST_USERS_SUCCESS';
export const POST_USERS_ERROR = 'POST_USERS_ERROR';
export const CLEAR_POST = 'CLEAR_POST';
